title: Site
# preset: pages
# unlisted: true


tabs:
  Pages:
    preset: pages
    unlisted: true
  Styles:
    type: fields
    fields:
      styles:
        type: structure
        columns:
          CSS:
            width: 1/2
          Name:
            width: 1/2
        fields:
          css:
            type: files
            max: 1
          name:
            type: text